import os
import secrets
import getpass

ENV_FILE = '.env'

def get_root_dir():
    """Return the absolute path to the project root directory."""
    return os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))

def main():
    print("--- Rheology Plotter Environment Initialization ---")
    
    root_dir = get_root_dir()
    env_path = os.path.join(root_dir, ENV_FILE)

    if os.path.exists(env_path):
        print(f"\nWARNING: A '{ENV_FILE}' file already exists at {env_path}.")
        print("Running this script will OVERWRITE the existing file and its secrets.")
        confirm = input("Are you sure you want to proceed? (y/N): ")
        if confirm.lower() != 'y':
            print("Initialization aborted.")
            return

    print("\nPlease enter a secure password for the Admin Area.")
    print("This password will be required to restore database backups.")
    while True:
        admin_password = getpass.getpass("Admin Password: ")
        if not admin_password.strip():
            print("Password cannot be empty. Please try again.")
            continue
            
        confirm_password = getpass.getpass("Confirm Password: ")
        if admin_password == confirm_password:
            break
        else:
            print("Passwords do not match. Please try again.\n")

    # Generate a cryptographically secure 24-byte (48-character hex) key for Flask
    secret_key = secrets.token_hex(24)

    env_content = f"""# Auto-generated by tools/init_env.py
ADMIN_PASSWORD={admin_password}
SECRET_KEY={secret_key}
"""

    try:
        with open(env_path, 'w') as f:
            f.write(env_content)
        
        # Ensure the file is only readable by the owner for security
        os.chmod(env_path, 0o600)
        
        print(f"\nSuccess! Successfully created '{ENV_FILE}' at {env_path}")
        print("The SECRET_KEY has been automatically generated and secured.")
    except Exception as e:
        print(f"\nError: Failed to write '{ENV_FILE}': {e}")

if __name__ == '__main__':
    main()